plugins {
    id 'java'
}

group = 'com.upgrademe'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(Test).configureEach {
    useJUnit()
}

dependencies {
    compileOnly 'org.robolectric:android-all:9-robolectric-4913185-2'
    testCompileOnly 'org.robolectric:android-all:9-robolectric-4913185-2'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.13'
}
